/**
 * setup.js - 自动解密 Trae 配置并保存到 .env
 *
 * 支持四版本自动探测(按优先级):
 *   1. cn      - Trae CN 国内版
 *   2. solo    - TRAE SOLO CN 独立部署版
 *   3. sg      - Trae 国际版(明文 JSON)
 *   4. solo-sg - TRAE SOLO 国际版
 *
 * 若 .env 中已存在 TRAE_EDITION,则按指定版本优先尝试。
 *
 * Usage: node setup.js
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const {
  decryptAuthData,
  getTraeCNDataDir,
  getTraeSGDataDir,
  getTraeSoloCNDataDir,
  getTraeSoloSGDataDir,
} = require('./src/trae-decrypt');

const ENV_PATH = path.join(__dirname, '.env');

// 版本 -> 数据目录 + API host 映射
const EDITIONS = [
  { name: 'cn',      dirFn: getTraeCNDataDir,      host: 'https://api.trae.cn' },
  { name: 'solo',    dirFn: getTraeSoloCNDataDir,  host: 'https://api.trae.cn' },
  { name: 'sg',      dirFn: getTraeSGDataDir,      host: 'https://api.trae.ai' },
  { name: 'solo-sg', dirFn: getTraeSoloSGDataDir,  host: 'https://api.trae.ai' },
];

/**
 * 读取 .env 中已有的某个 key(保留用户自定义设置)
 */
function readEnvValue(filePath, key) {
  try {
    if (!fs.existsSync(filePath)) return '';
    const content = fs.readFileSync(filePath, 'utf8');
    const regex = new RegExp(`^${key}=(.*)$`, 'm');
    const match = content.match(regex);
    return match ? match[1].trim() : '';
  } catch {
    return '';
  }
}

console.log('');
console.log('╔══════════════════════════════════════════╗');
console.log('║    Trae Local API - Auto Setup           ║');
console.log('╚══════════════════════════════════════════╝');
console.log('');

// 若 .env 已有 TRAE_EDITION,优先尝试该版本
const preferredEdition = readEnvValue(ENV_PATH, 'TRAE_EDITION');
let orderedEditions = EDITIONS;
if (preferredEdition) {
  console.log(`[setup] Found existing TRAE_EDITION=${preferredEdition}, trying it first`);
  orderedEditions = [
    ...EDITIONS.filter(e => e.name === preferredEdition),
    ...EDITIONS.filter(e => e.name !== preferredEdition),
  ];
}

let authData = null;
let edition = null;
let apiHost = '';
let lastError = null;

for (const ed of orderedEditions) {
  try {
    console.log(`[setup] Trying ${ed.name} edition...`);
    authData = decryptAuthData(ed.dirFn());
    edition = ed.name;
    apiHost = authData.host || ed.host;
    console.log(`[setup] ${ed.name.toUpperCase()} edition decrypt success`);
    break;
  } catch (e) {
    console.log(`[setup] ${ed.name} edition failed: ${e.message}`);
    lastError = e;
  }
}

if (!authData) {
  console.error('');
  console.error('Failed to read Trae config. Ensure:');
  console.error('  1. Trae IDE is installed and logged in');
  console.error('  2. Config file exists at one of:');
  for (const ed of EDITIONS) {
    console.error(`     ${ed.name}: ${path.join(ed.dirFn(), 'globalStorage', 'storage.json')}`);
  }
  if (lastError) console.error(`  Last error: ${lastError.message}`);
  process.exit(1);
}

// 保留用户已有的 PORT / API_KEY 设置(避免覆盖自定义配置)
const existingPort = process.env.PORT
  || readEnvValue(ENV_PATH, 'PORT')
  || '9220';
const existingApiKey = process.env.API_KEY
  || readEnvValue(ENV_PATH, 'API_KEY')
  || crypto.randomBytes(32).toString('base64url');
const existingHost = process.env.HOST
  || readEnvValue(ENV_PATH, 'HOST')
  || '127.0.0.1';
const existingDataDir = process.env.TRAE_DATA_DIR
  || readEnvValue(ENV_PATH, 'TRAE_DATA_DIR');

// Build .env content
const envContent = [
  '# Auto-generated by setup.js',
  `# Generated at: ${new Date().toISOString()}`,
  '',
  '# Trae Edition (cn/solo/sg/solo-sg)',
  `TRAE_EDITION=${edition}`,
  '',
  '# Auth credentials (auto-decrypted from Trae)',
  `TRAE_TOKEN=${authData.token || ''}`,
  `TRAE_REFRESH_TOKEN=${authData.refreshToken || ''}`,
  `TRAE_USER_ID=${authData.userId || ''}`,
  `TRAE_API_HOST=${apiHost}`,
  '',
  '# Token expiry info',
  `TRAE_TOKEN_EXPIRES=${authData.expiredAt || ''}`,
  `TRAE_REFRESH_EXPIRES=${authData.refreshExpiredAt || ''}`,
  '',
  '# Server config',
  `API_KEY=${existingApiKey}`,
  `PORT=${existingPort}`,
  `HOST=${existingHost}`,
  ...(existingDataDir ? [`TRAE_DATA_DIR=${existingDataDir}`] : []),
  '',
].join('\n');

// Write .env
fs.writeFileSync(ENV_PATH, envContent, 'utf8');
fs.chmodSync(ENV_PATH, 0o600);

console.log('');
console.log('=== Setup Complete ===');
console.log('');
console.log(`Edition:        ${edition.toUpperCase()}`);
console.log(`UserID:         ${authData.userId}`);
console.log(`Username:       ${authData.account?.username || 'N/A'}`);
console.log(`Region:         ${authData.userRegion?.region || 'N/A'}`);
console.log(`Token:          ${authData.token ? 'loaded' : 'N/A'}`);
console.log(`Token Expiry:   ${authData.expiredAt || 'N/A'}`);
console.log(`Refresh Expiry: ${authData.refreshExpiredAt || 'N/A'}`);
console.log(`API Host:       ${apiHost}`);
console.log(`Port:           ${existingPort}`);
console.log(`Host:           ${existingHost}`);
console.log('');
console.log(`Saved to: ${ENV_PATH}`);
console.log('');
console.log('Start the server with:');
console.log('  npm start');
console.log('');
