/**
 * auth.js - Authentication management
 *
 * Priority:
 * 1. TRAE_TOKEN from .env (pre-decrypted)
 * 2. Auto-decrypt from storage.json
 * 3. Manual TRAE_MANUAL_TOKEN
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { decryptAuthData, getTraeCNDataDir, getTraeSGDataDir, getTraeSoloCNDataDir, getTraeSoloSGDataDir } = require('./trae-decrypt');

const ENV_PATH = path.join(__dirname, '..', '.env');

let authData = null;
let refreshMutex = false;

/**
 * Initialize auth
 */
function initAuth(edition, manualToken) {
  // Priority 1: TRAE_TOKEN from env (set by setup.js or manually)
  if (process.env.TRAE_TOKEN) {
    console.log('[auth] Using TRAE_TOKEN from .env');
    authData = {
      token: process.env.TRAE_TOKEN,
      refreshToken: process.env.TRAE_REFRESH_TOKEN || null,
      userId: process.env.TRAE_USER_ID || '',
      expiredAt: process.env.TRAE_TOKEN_EXPIRES || null,
      refreshExpiredAt: process.env.TRAE_REFRESH_EXPIRES || null,
      host: process.env.TRAE_API_HOST || '',
    };
    _logAuth();
    return;
  }

  // Priority 2: Manual token
  if (manualToken) {
    console.log('[auth] Using manual token from env');
    authData = { token: manualToken, refreshToken: null, userId: '' };
    return;
  }

  // Priority 3: Auto-decrypt from storage.json
  try {
    if (edition === 'cn') {
      authData = decryptAuthData(getTraeCNDataDir());
      console.log('[auth] Using CN edition auth data (decrypted from storage.json)');
    } else if (edition === 'solo') {
      authData = decryptAuthData(getTraeSoloCNDataDir());
      console.log('[auth] Using SOLO CN edition auth data (decrypted from storage.json)');
    } else if (edition === 'solo-sg') {
      authData = decryptAuthData(getTraeSoloSGDataDir());
      console.log('[auth] Using SOLO SG edition auth data (decrypted from storage.json)');
    } else {
      authData = decryptAuthData(getTraeSGDataDir());
      console.log('[auth] Using SG edition auth data');
    }
    _logAuth();

    // Auto-save to .env for next time
    _saveEnv(edition);
  } catch (err) {
    console.error(`[auth] Failed to load auth data: ${err.message}`);
    throw err;
  }
}

function _logAuth() {
  if (authData.token) console.log('[auth] Token loaded');
  if (authData.userId) console.log(`[auth] UserID: ${authData.userId}`);
  if (authData.expiredAt) console.log(`[auth] Token expires: ${authData.expiredAt}`);
}

function _saveEnv(edition) {
  try {
    // 保留用户已有的 PORT / API_KEY 设置(避免覆盖自定义配置)
    const existingPort = process.env.PORT || (fs.existsSync(ENV_PATH) ? readEnvValue(ENV_PATH, 'PORT') : '') || '9220';
    const existingApiKey = process.env.API_KEY || (fs.existsSync(ENV_PATH) ? readEnvValue(ENV_PATH, 'API_KEY') : '') || crypto.randomBytes(32).toString('base64url');
    const existingHost = process.env.HOST || (fs.existsSync(ENV_PATH) ? readEnvValue(ENV_PATH, 'HOST') : '') || '127.0.0.1';
    const existingDataDir = process.env.TRAE_DATA_DIR || (fs.existsSync(ENV_PATH) ? readEnvValue(ENV_PATH, 'TRAE_DATA_DIR') : '');

    const lines = [
      '# Auto-generated by trae-local-api',
      `TRAE_EDITION=${edition}`,
      `TRAE_TOKEN=${authData.token || ''}`,
      `TRAE_REFRESH_TOKEN=${authData.refreshToken || ''}`,
      `TRAE_USER_ID=${authData.userId || ''}`,
      `TRAE_API_HOST=${authData.host || ''}`,
      `TRAE_TOKEN_EXPIRES=${authData.expiredAt || ''}`,
      `TRAE_REFRESH_EXPIRES=${authData.refreshExpiredAt || ''}`,
      `API_KEY=${existingApiKey}`,
      `PORT=${existingPort}`,
      `HOST=${existingHost}`,
      ...(existingDataDir ? [`TRAE_DATA_DIR=${existingDataDir}`] : []),
    ];
    fs.writeFileSync(ENV_PATH, lines.join('\n') + '\n', 'utf8');
    fs.chmodSync(ENV_PATH, 0o600);
    console.log(`[auth] Saved credentials to ${ENV_PATH}`);
  } catch (e) {
    console.warn(`[auth] Could not save .env: ${e.message}`);
  }
}

/**
 * 简单读取 .env 中某个 key 的值(不引入新依赖)
 */
function readEnvValue(filePath, key) {
  try {
    const content = fs.readFileSync(filePath, 'utf8');
    const regex = new RegExp(`^${key}=(.*)$`, 'm');
    const match = content.match(regex);
    return match ? match[1].trim() : '';
  } catch {
    return '';
  }
}

function getToken() { return authData ? authData.token : null; }
function getUserId() { return authData ? authData.userId : null; }
function getRefreshToken() { return authData ? authData.refreshToken : null; }

function needsRefresh() {
  if (!authData || !authData.expiredAt) return false;
  const expiry = new Date(authData.expiredAt).getTime();
  return Date.now() >= expiry - 30 * 60 * 1000;
}

async function refreshToken() {
  if (refreshMutex) return;
  refreshMutex = true;
  try {
    const rt = authData.refreshToken;
    if (!rt) { console.error('[auth] No refreshToken'); return; }

    // CN edition uses api.trae.cn for token refresh, SG uses api-sg-central.trae.ai
    const refreshHost = authData.host || process.env.TRAE_API_HOST || 'https://api.trae.cn';

    console.log('[auth] Refreshing token...');
    const resp = await fetch(`${refreshHost}/cloudide/api/v3/trae/oauth/ExchangeToken`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        ClientID: 'ono9krqynydwx5',
        RefreshToken: rt,
        ClientSecret: '-',
        UserID: authData.userId || '',
      }),
    });

    if (!resp.ok) {
      console.error(`[auth] Refresh failed: ${resp.status} ${await resp.text()}`);
      return;
    }

    const data = await resp.json();
    if (data.Result) {
      authData.token = data.Result.Token;
      authData.refreshToken = data.Result.RefreshToken || authData.refreshToken;
      authData.expiredAt = data.Result.TokenExpireAt
        ? new Date(data.Result.TokenExpireAt).toISOString() : authData.expiredAt;
      console.log('[auth] Token refreshed');
      // Update .env
      _saveEnv(process.env.TRAE_EDITION || 'cn');
    }
  } catch (err) {
    console.error(`[auth] Refresh error: ${err.message}`);
  } finally {
    refreshMutex = false;
  }
}

module.exports = { initAuth, getToken, getUserId, getRefreshToken, needsRefresh, refreshToken };
